### ISSUE TITLE
HA 2024.12.1 - No module named 'bounciepy'

### ISSUE THREAD

**Issue by themoosman** [mandarons/ha-bouncie#53]
**Describe the bug**
After upgrading to HA 2024.12.1, the bounce integration does not load.  Restarting the HA instance or reinstalling the bounce integration does not fix the issue.

**To Reproduce**

1. Upgrade to HA 2024.12.1 and reboot

**Additional context**

HA is installed using the container method.

Log message from HA

```
2024-12-07 08:10:47.767 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'bouncie': Unable to import component: No module named 'bounciepy'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/bouncie/__init__.py", line 12, in <module>
    from .coordinator import BouncieDataUpdateCoordinator
  File "/config/custom_components/bouncie/coordinator.py", line 6, in <module>
    from bounciepy import AsyncRESTAPIClient
ModuleNotFoundError: No module named 'bounciepy'
```

**Comment by themoosman** [comment]
This issue looks to be a larger issue with HA 2024.12

https://community.home-assistant.io/t/wth-is-going-on-with-docker-container-installs-and-third-party-integrations-that-need-python-modules/806430

**Comment by themoosman** [comment]
For anyone else with this issue, mount an empty `.dockerenv` to `/` in the container and it will fix the issue.
